## IRIS 데이터셋

In [183]:
# 모듈로딩
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

In [184]:
# 데이터 불러오기
iris=load_iris(return_X_y=True, as_frame=True)
type(iris), iris[0].info(), iris[1]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


(tuple,
 None,
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 145    2
 146    2
 147    2
 148    2
 149    2
 Name: target, Length: 150, dtype: int32)

In [185]:
# 특성인 4개열만
data=iris[0]
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [186]:
# 라벨 열
target=iris[1]
target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

- 0: setosa ,1: vergincolor , 2: virginica 

In [187]:
# 타켓 데이터 정보 확인
print(target.head(3),target.unique(),target.value_counts(),sep='\n\n')

0    0
1    0
2    0
Name: target, dtype: int32

[0 1 2]

0    50
1    50
2    50
Name: target, dtype: int64


In [188]:
# 데이터 => petal_length (cm), petal_width (cm)
# 타켓 => 0, 2
# 이거는 행이 150개
data=data.loc[:,data.columns[2:]]

print(f"data => {data.shape}")

data => (150, 2)


In [189]:
# x 100행 맞추기
data=data.drop(index=range(50,100),axis=0) # 50행에서 99행 삭제
print(f"data의 차원 {data.shape}")

data의 차원 (100, 2)


In [190]:
# y 100행으로 맞추기
target=target.drop(range(50,100)) # 50~99 삭제
print(f"target의 차원 {target.shape}")

target의 차원 (100,)


### 로지스틱 회귀

In [191]:
# 모델 객체 생성
model=LogisticRegression()

In [192]:
# 데프를 배열로
data=np.array(data).reshape(-1,2)

In [193]:
# 모델 훈련
model.fit(data,target)

LogisticRegression()

In [194]:
# 모델 평가
model.score(data,target)

1.0

In [195]:
# 모델 예측
print(model.predict([[4.5,3]]))
print(model.predict([[1.4,0.2]]))

[2]
[0]


In [196]:
# 훈련/테스트 데이터 75:25 비율로 만들기
train_x,test_x,train_y,test_y=train_test_split(data,target,random_state=42,stratify=target)

print(train_x.shape)
print(test_x.shape)

(75, 2)
(25, 2)


- stratify=옵션은 분류 항복 비율 맞추어서 데이터셋 설정

In [197]:
# 훈련/테스트 데이터 80:20 비율로 만들기
train_x,test_x,train_y,test_y=train_test_split(data,target,random_state=42,test_size=0.2)

print(train_x.shape)
print(test_x.shape)

(80, 2)
(20, 2)


In [203]:
# 회귀 모델 객체 생성
model=LogisticRegression()

In [204]:
# 모델 훈련
model.fit(train_x,train_y)

LogisticRegression()

In [206]:
# 모델평가
model.score(train_x,train_y)

1.0

In [207]:
# 테스트 데이터로 예측값
model.predict(test_x)

array([2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0])

In [208]:
# 새로운 값을 집어 넣고 예측하기
print(model.predict([[1.2,0.4]]))
print(model.predict([[5.4,1.2]]))
print(model.predict([[3.2,0.8]]))
print(model.predict([[9,3.0]]))

[0]
[2]
[0]
[2]


### 다중 로지스틱 분석

In [225]:
# 아이리스 데이터를 다시 불러옴
iris=load_iris(return_X_y=True, as_frame=True)

print(f"특성\n{iris[0]}")
print(f"타겟\n{iris[1]}")

특성
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
타겟
0      0
1      0
2      0
3      

In [226]:
# input과 target 지정
input=np.array(iris[0].iloc[:,[2,3]]).reshape(-1,2)
target=np.array(iris[1])

print(f"input\n{input}")
print(f"target\n{target}")

input
[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.

In [227]:
# 훈련/테스트 데이터 나누기
train_input,test_input,trian_target,test_target=train_test_split(input,target,random_state=42,stratify=target)

In [228]:
# 모델 객체 생성
model=LogisticRegression(solver='lbfgs',max_iter=100)

# lbfgs는 준 뉴턴 방식의 최적화 알고리즘

In [229]:
# 모델 학습
model.fit(train_input,trian_target)

LogisticRegression()

In [230]:
# 학습후 확인
print(f"분류 종류 : {model.classes_}")
print(f"가중치 값 : {model.coef_}")
print(f"절편   값 : {model.intercept_}")
print(f"특성 갯수 : {model.n_features_in_}")

분류 종류 : [0 1 2]
가중치 값 : [[-2.54289023 -1.08109257]
 [ 0.08210092 -0.79934156]
 [ 2.46078931  1.88043413]]
절편   값 : [ 10.34385242   2.89054114 -13.23439355]
특성 갯수 : 2


- 각 분류(꽃 종류)마다 회귀식이 다르다는 것을 알 수 있음

In [231]:
# 모델평가
model.score(train_input,trian_target)

0.9732142857142857

In [232]:
# 모델예측
model.predict(test_input)

array([0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1,
       2, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 1])

In [219]:
# 모델평가(테스트 데이터)
model.score(test_input,test_target)

0.9473684210526315

In [220]:
# 모델예측
model.predict([[2.3,4.5]])

# 2(virginica)로 예측함

array([2])

In [221]:
# 결정함수
ret=model.decision_function([[2.3,4.5]])
print(np.round(ret,3))

[[-0.37  -0.518  0.887]]


In [233]:
# y=Wx+b: 모델 파라미터
print(f"petal length (cm)은 2.3, petal width (cm)은 4.5인 예측값은????")
print(f"0(setosa)의 예측값은 {(model.coef_[0,0]*2.3+model.coef_[0,1]*4.5)+model.intercept_[0]}로 나옴")
print(f"1(vergincolor)의 예측값은 {(model.coef_[1,0]*2.3+model.coef_[1,1]*4.5)+model.intercept_[1]}로 나옴")
print(f"2(virginica)의 예측값은 {(model.coef_[2,0]*2.3+model.coef_[2,1]*4.5)+model.intercept_[2]}로 나옴")

petal length (cm)은 2.3, petal width (cm)은 4.5인 예측값은????
0(setosa)의 예측값은 -0.3697116929338726로 나옴
1(vergincolor)의 예측값은 -0.5176637780723956로 나옴
2(virginica)의 예측값은 0.8873754710063313로 나옴


In [255]:
# 시그모이드 함수/ 소프트 맥스 후 결과 확인
from scipy.special import softmax, expit

sigValue2=softmax(ret) # 확률값을 다 더하면 1
print(np.round(sigValue2))

print(np.round(expit(ret))) # 각 분류가 될 확률을 나타낸 것
print(expit(ret))

[[0. 0. 1.]]
[[0. 1. 1.]]
[[0.00347941 0.83315512 0.98286335]]


### 모든 열에 대해 분류하기

In [239]:
# 아이리스 데이터를 다시 불러옴
iris=load_iris(return_X_y=True, as_frame=True)
input=np.array(iris[0]).reshape(-1,4)
target=np.array(iris[1])
train_input,test_input,trian_target,test_target=train_test_split(input,target,random_state=42)


In [240]:
# 데이터 불러오기 다른 방법
iris=load_iris()
input=iris.data
target=iris.target
train_input,test_input,trian_target,test_target=train_test_split(input,target,random_state=42,stratify=target)

In [242]:
# 모델 객체 생성(학습횟수는 500)
model=LogisticRegression(max_iter=500)

In [243]:
# 모델 학습
model.fit(input,target)

LogisticRegression(max_iter=500)

In [244]:
# 학습후 확인
print(f"분류 종류 : {model.classes_}")
print(f"가중치 값 : {model.coef_}")
print(f"절편   값 : {model.intercept_}")
print(f"특성 갯수 : {model.n_features_in_}")


분류 종류 : [0 1 2]
가중치 값 : [[-0.42319387  0.96707765 -2.51718312 -1.07957563]
 [ 0.53435852 -0.32151325 -0.20652326 -0.9440541 ]
 [-0.11116466 -0.64556441  2.72370638  2.02362972]]
절편   값 : [  9.84913638   2.23773829 -12.08687468]
특성 갯수 : 4


In [248]:
# 새로운 데이터
new_data=[6.7,3,5.2,2.3]

# 결정함수
ret=model.decision_function([new_data])
print(ret)

# 예측값
print(f"예측값은 {model.predict([new_data])}")

[[-5.65740573  1.6081553   4.04925043]]
예측값은 [2]


In [249]:
# 소프트맥스
from scipy.special import softmax

result=[]
for i in range(3):
    y=model.coef_[i][0]*new_data[0]+\
      model.coef_[i][1]*new_data[1]+\
        model.coef_[i][2]*new_data[2]+\
            model.coef_[i][3]*new_data[3]+\
                model.intercept_[i]
    result.append(y)
    print(f"{i}의 예측값={y}")

0의 예측값=-5.65740573130655
1의 예측값=1.6081553046515522
2의 예측값=4.049250426654913


In [252]:
# 분류에 속할 확률
np.round(softmax(ret),2),np.round(softmax(result),2)

(array([[0.  , 0.08, 0.92]]), array([0.  , 0.08, 0.92]))

- ret는 결정 함수를 사용하여 예측한 것이고  
  result는 회귀계수와 절편을 활용한 값 구하기로  
  2개의 값은 서로 동일함